### ISSUE TITLE
Issue 15: Seperate GUI file

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#35]
separate the GUI out from the file!

**Comment by jorn600** [comment]
please remove that comment, it will look like its still blocked

**Comment by joseph-allen** [comment]
good call thanks @jorn600

**Comment by ayush-seth** [comment]
so the buttons being drawn should not be in the main sketch and have a separate class ?

**Comment by joseph-allen** [comment]
yeah, for now it is okay but as this main file grows it becomes clear that we don't need to see certain things :) also for Open Source projects many separate files can be very helpful!

**Comment by ayush-seth** [comment]
I think these should remain in the main sketch because they are elements that are drawn, perhaps we could make a function `createButtons()` that will populate the array list and will be called in setup instead of doing all the work inside setup, but the `createButtons()` function still needs to be in the main sketch
