### ISSUE TITLE
Calculator should add numbers

### ISSUE THREAD

**Issue by akathewb** [joezcool02/OurCalculator#68]
Calculator should 
add numbers
then display the total when the = button is pressed
when a new number is pressed it should clear the total and start adding the new numbers

(I already wrote some code to do this, would like to send a pull request and see if I'm doing the git collaboration right, as I reread the git tutorials you all posted)

**Comment by akathewb** [comment]
Just discovered the eval branch that has a bunch of updates in it including adding.
Should I be branching off the eval branch when working locally?

**Comment by ayush-seth** [comment]
It's up to you, you can branch off master or eval, it doesn't matter because you will delete your branch at the end anyways, regarding your PR, we already have a pretty functional calculator, checkout eval branch on your local system using git cli and then open the project and run it to see what works and what doesn't

**Comment by joseph-allen** [comment]
we should pull the eval branch back into master at some point, beginners won't know to check the eval branch and Iwouldn't expect it to be there

**Comment by ayush-seth** [comment]
since the calculator is essentially bug free (we do not have any known bugs to fix), let's just merge them

**Comment by joseph-allen** [comment]
go for it, if we are going to work in separate branches it needs to be in the readme or something otherwise new contributors are lost
